# Generated by Django 5.0.4 on 2026-08-19 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('country_code', models.CharField(max_length=3, verbose_name='country code')),
                ('currency', models.CharField(max_length=3)),
                ('calling_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AlterModelOptions(
            name='members',
            options={'ordering': ['-created_at'], 'verbose_name': 'member', 'verbose_name_plural': 'members'},
        ),
        migrations.AlterField(
            model_name='members',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='protest_app.citiesmodel'),
        ),
        migrations.AddField(
            model_name='citiesmodel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='protest_app.countrymodel'),
        ),
        migrations.AddField(
            model_name='members',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='protest_app.countrymodel'),
        ),
        migrations.CreateModel(
            name='StatesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='protest_app.countrymodel')),
            ],
        ),
        migrations.AddField(
            model_name='citiesmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='protest_app.statesmodel'),
        ),
        migrations.AlterField(
            model_name='members',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='protest_app.statesmodel'),
        ),
        migrations.AddIndex(
            model_name='members',
            index=models.Index(fields=['city', '-created_at'], name='protest_app_city_id_fbf100_idx'),
        ),
        migrations.AddIndex(
            model_name='members',
            index=models.Index(fields=['state', '-created_at'], name='protest_app_state_i_afd76e_idx'),
        ),
        migrations.AddIndex(
            model_name='members',
            index=models.Index(fields=['country', '-created_at'], name='protest_app_country_1c6ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='members',
            index=models.Index(fields=['is_deleted'], name='protest_app_is_dele_b923c1_idx'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
